### PR TITLE
Fix issue so thaat you can demonstrate auto association management

### PR DESCRIPTION
**Pull request by vladmihalcea**
To test it:

1. Make sure you run `mvn clean test-compile` so that you can validate that Bytecode enhancement was applied (this might not be the case if you run it from your IDE)
2. The auto-association management applies hen you use the setter, but not if you manipulate the List directly, like after you called the getter.

### CODE REVIEW

**Comment by yanaga** [comment]
Hum... So it's just the setter, and not the List that gets instrumented? Setter instrumentation is not that useful for collection handling...

And I also strongly advocate against these kinds of setters too :-)

**Comment by vladmihalcea** [comment]
I'm not a fan of this feature. I think it's much better if the [addChild/removeChild methods are always added to the parent](https://vladmihalcea.com/2015/03/05/a-beginners-guide-to-jpa-and-hibernate-cascade-types/), and this way we can remove the setter altogether.

In fact, the other two features are seldom useful because:

1. If you strive to limit the PersistenceContext to a very small size, the default dirty checking mechanism is sufficient, so you don't really need the BE one
2. For lazy fields, [you can always use subentities](https://vladmihalcea.com/2016/09/13/the-best-way-to-handle-the-lazyinitializationexception/)
3. For lazy parent-side  @OneToOne, you can use [`@MapsId`](https://vladmihalcea.com/2016/07/26/the-best-way-to-map-a-onetoone-relationship-with-jpa-and-hibernate/)

**Comment by vladmihalcea** [comment]
These [Hibernate 5 features are more interesting](http://stackoverflow.com/questions/31965179/whats-new-in-hibernate-orm-5):

* hibernate-spatial integration
*  Java 8 Date and Time API
* Ad-hoc joins
* Multi-entity load by id
* Support for JCache
* Session-level batch size
* Global timezone setting (e.g. UTC) for Timestamp and Time
* Distinct pass-through
* Better JPQL and HQL parsing for constant value resolution

Check out the StackOverflow answer for some links to these features.

**Comment by yanaga** [comment]
Well, I guess I'll have to do an excitement-- about the bytecode enhancement and stick to the other features :-)

**Comment by vladmihalcea** [comment]
For bytecode enhancement, the entity attribute lazy loading is quite cool. I'd show that for instance.

**Pull request merged**
